export {
  getRentalDashboard,
  createRentalAsset,
  updateRentalAsset,
  createRentalContract,
  updateRentalContract,
  dispatchRentalContract,
  returnRentalContract,
  closeRentalContract,
  createRentalGuarantee,
  updateRentalGuarantee,
  deleteRentalGuarantee,
  createRentalEvent,
  getRentalTimeline,
  createRentalBackup,
  recomputeAssetAllocations,
} from "./rentalService";
