export {
  crmCreateLead,
  crmUpdateLead,
  crmDeleteLeadCascade,
  crmGetLeadDossier,
  crmAddLeadNote,
  crmListStages,
  crmCreateStage,
  crmUpdateStage,
  crmDeleteStage,
  crmReorderStages,
  crmListServiceTypes,
  crmCreateServiceType,
  crmUpdateServiceType,
  crmDeleteServiceType,
  crmGetService,
  crmGetServiceByLead,
  crmUpdateServiceOperationalControl,
  crmCreateDocumentUpload,
  crmFinalizeDocumentUpload,
  crmListDocuments,
  crmGetDocumentDownloadUrl,
  crmUpdateDocumentMirrorFlag,
  crmGetServiceMirror,
  crmGetCRMStats,
} from "./crmService";
