export {
  crmCreateLead,
  crmUpdateLead,
  crmDeleteLeadCascade,
  crmGetLeadDossier,
  crmAddLeadNote,
  crmListStages,
  crmCreateStage,
  crmUpdateStage,
  crmDeleteStage,
  crmReorderStages,
  crmListServiceTypes,
  crmCreateServiceType,
  crmUpdateServiceType,
  crmDeleteServiceType,
  crmGetService,
  crmGetServiceByLead,
  crmUpdateServiceOperationalControl,
  crmCreateDocumentUpload,
  crmFinalizeDocumentUpload,
  crmListDocuments,
  crmGetDocumentDownloadUrl,
  crmUpdateDocumentMirrorFlag,
  crmGetServiceMirror,
  crmListLeads,
  crmPublicMirror,
  crmGetCRMStats,
} from "./crmService";

export {
  crmListCustomers,
  crmGetCustomer,
  crmCreateCustomer,
  crmUpdateCustomer,
  crmDeleteCustomer,
  crmListMandantes,
  crmGetMandante,
  crmCreateMandante,
  crmUpdateMandante,
  crmDeleteMandante,
} from "./customerService";
